name: Build Flutter App (Android & iOS)
on:
  push: 
    branches:
      - main
permissions:
  contents: write
jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Read APK name from name.txt
        id: read_apk_name
        run: |
          APK_NAME=$(cat assets/app/name.txt)
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Rename APK and move to apk_release/
        run: |
          mkdir -p apk_release
          cp build/app/outputs/flutter-apk/app-release.apk apk_release/${{ steps.read_apk_name.outputs.apk_name }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: apk_release/${{ steps.read_apk_name.outputs.apk_name }}.apk

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android]
    name: Create GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read APK name from name.txt
        id: read_apk_name
        run: |
          APK_NAME=$(cat assets/app/name.txt)
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: release/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Mobile App Release v1.0.${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
          files: |
            release/${{ steps.read_apk_name.outputs.apk_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
